# Default values for allure-docker-helm-chart.
# This is a YAML-formatted file.

ingress:
  # -- Enable or disable ingress for Allure services
  enabled: true
  
  # -- Hostname for the Allure UI service
  hostnameUi: allure.example.com
  
  # -- Hostname for the Allure API service
  hostnameApi: allure-api.example.com
  
  tls:
    # -- Enable or disable TLS for the ingress
    enabled: true
    
    # -- Name of the Kubernetes secret that contains the TLS certificate
    secretName: example-ssl

service:
  # -- Port for the Allure API service
  apiPort: 6060
  
  # -- Port for the Allure UI service
  uiPort: 7070
  
  # -- ClusterIP for the service (set to "None" for headless service)
  clusterIP: "None"

deployment:
  # -- Number of replicas for the Allure deployment
  replicas: 1
  
  containers:
    allure:
      # -- Docker image for the Allure backend service
      image: "frankescobar/allure-docker-service"
      
      # -- Image pull policy (Always, IfNotPresent, Never)
      imagePullPolicy: Always
      
      # -- Container port for the Allure API
      containerPort: 5050
    
    allureUi:
      # -- Docker image for the Allure UI service
      image: "frankescobar/allure-docker-service-ui"
      
      # -- Image pull policy (Always, IfNotPresent, Never)
      imagePullPolicy: Always
      
      # -- Container port for the Allure UI
      containerPort: 5252

persistentVolume:
  # -- Size of the Persistent Volume Claim (PVC)
  size: 3Gi
  
  # -- Storage class for the Persistent Volume
  storageClass: "default"

secrets:
  # -- Username for the security authentication
  securityUser: "my_username"
  
  # -- Password for the security authentication
  securityPass: "my_password"
  
  # -- Username for the viewer authentication
  viewerUser: "view_user"
  
  # -- Password for the viewer authentication
  viewerPass: "view_pass"

config:
  # -- Interval in seconds to check for new test results (set to NONE for no checks)
  checkResultsEverySeconds: NONE
  
  # -- Keep history of previous test results (1 = enabled, 0 = disabled)
  keepHistory: "1"
  
  # -- URL prefix for the API endpoints
  urlPrefix: "/allure-api"
  
  # -- Enable TLS security (1 = enabled, 0 = disabled)
  tls: "1"
  
  # -- Enable authentication security (1 = enabled, 0 = disabled)
  securityEnabled: "1"
  
  # -- Make viewer endpoints public (1 = enabled, 0 = disabled)
  makeViewerEndpointsPublic: "0"

  ui:
    # -- Public API URL for the Allure UI
    publicApiUrl: "https://allure-api.example.com/allure-api"
    
    # -- Prefix for the public API URL
    publicApiUrlPrefix: "/allure-api"
    
    # -- URL prefix for the Allure UI
    urlPrefix: "/allure-ui"