apiVersion: v1
kind: ConfigMap
metadata:
  name: allure-config-map
  namespace: allure-docker-service
data:
  CHECK_RESULTS_EVERY_SECONDS: {{ .Values.config.checkResultsEverySeconds | quote }}
  KEEP_HISTORY: {{ .Values.config.keepHistory | quote }}
  URL_PREFIX: {{ .Values.config.urlPrefix | quote }}
  TLS: {{ .Values.config.tls | quote }}
  SECURITY_ENABLED: {{ .Values.config.securityEnabled | quote }}
  MAKE_VIEWER_ENDPOINTS_PUBLIC: {{ .Values.config.makeViewerEndpointsPublic | quote }}