apiVersion: v1
kind: ConfigMap
metadata:
  name: allure-config-ui-map
  namespace: allure-docker-service
data:
  ALLURE_DOCKER_PUBLIC_API_URL: {{ .Values.config.ui.publicApiUrl | quote }}
  ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: {{ .Values.config.ui.publicApiUrlPrefix | quote }}
  URL_PREFIX: {{ .Values.config.ui.urlPrefix | quote }}