apiVersion: apps/v1
kind: Deployment
metadata:
  name: allure-deployment
  namespace: allure-docker-service
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: allure
  template:
    metadata:
      labels:
        app: allure
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: allure
          image: {{ .Values.deployment.containers.allure.image }}
          imagePullPolicy: {{ .Values.deployment.containers.allure.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.containers.allure.containerPort }}
          envFrom:
            - configMapRef:
                name: allure-config-map
            - secretRef:
                name: allure-secret
          volumeMounts:
            - name: reports-volume
              mountPath: /app/projects
        - name: allure-ui
          image: {{ .Values.deployment.containers.allureUi.image }}
          imagePullPolicy: {{ .Values.deployment.containers.allureUi.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.containers.allureUi.containerPort }}
          envFrom:
            - configMapRef:
                name: allure-config-ui-map
      volumes:
        - name: reports-volume
          persistentVolumeClaim:
            claimName: allure-persistent-volume-claim