{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: allure-ingress-service-ui
  namespace: allure-docker-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.tls.enabled | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  rules:
    - host: {{ .Values.ingress.hostnameUi | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: allure-service
                port:
                  number: {{ .Values.service.uiPort }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostnameUi | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: allure-ingress-service-api
  namespace: allure-docker-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.tls.enabled | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  rules:
    - host: {{ .Values.ingress.hostnameApi | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: allure-service
                port:
                  number: {{ .Values.service.apiPort }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostnameApi | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
{{- end }}
