apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allure-persistent-volume-claim
  namespace: allure-docker-service
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  storageClassName: {{ .Values.persistentVolume.storageClass | default "standard" }}