apiVersion: v1
kind: Service
metadata:
  name: allure-service
  namespace: allure-docker-service
spec:
  type: ClusterIP
  ports:
    - name: allure-api
      port: {{ .Values.service.apiPort }}
      targetPort: 5050
    - name: allure-ui
      port: {{ .Values.service.uiPort }}
      targetPort: 5252
  selector:
    app: allure